import type { Metadata } from "next";
import "./globals.css";
import DesktopSidebar from "../src/Navbar/DeskTopNavbar/DesktopSidebar";
import MobileSidebar from "@/src/Navbar/MobileNavbar/MobileSidebar";
import { inter, dmSans, aneklatin } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-background text-foreground font-inter">
      <body className={`${inter.variable} ${dmSans.variable} ${aneklatin.variable}`}>

        {/* GLOBAL NAV (OUTSIDE MAIN) */}
        <DesktopSidebar />
        <MobileSidebar />
        <main className="min-h-screen md:ml-[270px]">
          {children}
        </main>

      </body>
    </html>
  );
}
