import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DesktopSidebar from "../src/Navbar/DeskTopNavbar/DesktopSidebar";
import MobileSidebar from "@/src/Navbar/MobileNavbar/MobileSidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased bg-backgroundcolor text-foreground">

        {/* GLOBAL NAV (OUTSIDE MAIN) */}
        <DesktopSidebar />
        <MobileSidebar />
        <main className="min-h-screen md:ml-[270px]">
          {children}
        </main>

      </body>
    </html>
  );
}
